---
language: python
services: docker

env:
  matrix:
    - TEST_DISTRO: centos:7
    - TEST_DISTRO: centos:8
    - TEST_DISTRO: amazonlinux:2
    - TEST_DISTRO: debian:8
    - TEST_DISTRO: debian:9
    - TEST_DISTRO: fedora:25
    - TEST_DISTRO: fedora:26
    - TEST_DISTRO: fedora:27
    - TEST_DISTRO: fedora:28
    - TEST_DISTRO: fedora:29
    - TEST_DISTRO: fedora:30
    - TEST_DISTRO: fedora:31
    - TEST_DISTRO: fedora:32
    - TEST_DISTRO: ubuntu:16.04
    - TEST_DISTRO: ubuntu:18.04
    - TEST_DISTRO: ubuntu:20.04

install:
  - pip install -r molecule/requirements.txt

script:
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
