---
name: Molecule CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_CALLBACK_WHITELIST: profile_tasks
      PY_COLORS: '1'
      ANSIBLE_FORCE_COLOR: '1'
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        test_distro:
          - centos:6
          - centos:7
          - centos:8
          - amazonlinux:1
          - amazonlinux:2
          - debian:8
          - debian:9
          - debian:10
          - fedora:25
          - fedora:26
          - fedora:27
          - fedora:28
          - fedora:29
          - fedora:30
          - fedora:31
          - fedora:32
          - ubuntu:16.04
          - ubuntu:18.04
          - ubuntu:20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r molecule/requirements.txt
      - name: Test with molecule
        run: molecule test --all
        env:
          TEST_DISTRO: ${{ matrix.test_distro }}
      - name: Notify Ansible Galaxy
        uses: joelwmale/webhook-action@1.0.0
        env:
          WEBHOOK_URL: https://galaxy.ansible.com/api/v1/notifications/
          data: "{'deployment': 'finished', 'project': 'actions'}"
